splunk:
  conf:
    inputs:
      directory: /opt/splunkforwarder/etc/system/local
      content:
        monitor:///var/log/containers/mcp-jsonrpc.log:
          disabled: 0
          index: mcp
          sourcetype: "mcp:jsonrpc"
          host: ollama-mcp
        monitor:///var/log/containers/ollama.log:
          disabled: 0
          index: llm
          sourcetype: "ollama:server"
          host: ollama-server
    outputs:
      directory: /opt/splunkforwarder/etc/system/local
      content:
        tcpout:
          defaultGroup: splunk-indexer
        tcpout:splunk-indexer:
          server: "security-range-splunk:9997"
