splunk:
  hec:
    enable: true
    ssl: false
    port: 8088
    token: f4e45204-7cfa-48b5-bfbe-95cf03dbcad7

  indexes:
    directories:
      mcp:
        datatype: event
        homePath: $SPLUNK_DB/mcp/db
        coldPath: $SPLUNK_DB/mcp/colddb
        thawedPath: $SPLUNK_DB/mcp/thaweddb
      llm:
        datatype: event
        homePath: $SPLUNK_DB/llm/db
        coldPath: $SPLUNK_DB/llm/colddb
        thawedPath: $SPLUNK_DB/llm/thaweddb
